// RSS 피드 수집 불가 시 사용할 샘플 뉴스 데이터

const sampleArticles = [
  {
    title: 'U.S. Department of Energy Announces $3.5 Billion for Grid-Scale Battery Storage',
    link: 'https://example.com/us-battery-storage',
    snippet: 'The DOE unveiled a massive investment plan to deploy grid-scale battery storage systems across 15 states, aiming to store 50GW of renewable energy by 2030 as part of the Inflation Reduction Act rollout.',
    source: 'Renewable Energy World',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 1 * 3600000).toISOString(),
    timestamp: Date.now() - 1 * 3600000,
    fullText: 'U.S. Department of Energy Announces $3.5 Billion for Grid-Scale Battery Storage The DOE unveiled a massive investment plan to deploy grid-scale battery storage systems across 15 states united states',
  },
  {
    title: 'European Commission Approves €20B Green Hydrogen Strategy for 2030',
    link: 'https://example.com/eu-hydrogen',
    snippet: 'The European Commission has formally adopted a landmark green hydrogen strategy allocating €20 billion to develop electrolyzer capacity and hydrogen infrastructure across member states, targeting 10 million tonnes of domestic production.',
    source: 'Recharge News',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 2 * 3600000).toISOString(),
    timestamp: Date.now() - 2 * 3600000,
    fullText: 'European Commission Approves €20B Green Hydrogen Strategy for 2030 The European Commission has formally adopted a landmark green hydrogen strategy europe european eu',
  },
  {
    title: '한국 해상풍력 8.2GW 로드맵 확정 — 산업부 발표',
    link: 'https://example.com/kr-offshore-wind',
    snippet: '산업통상자원부는 2030년까지 해상풍력 8.2GW 보급 로드맵을 확정 발표했다. 전남·경북·제주 해역에 대규모 단지를 조성하며, 지역 주민 수용성과 환경영향평가 절차를 강화할 방침이다.',
    source: '전기신문',
    lang: 'ko',
    image: null,
    pubDate: new Date(Date.now() - 3 * 3600000).toISOString(),
    timestamp: Date.now() - 3 * 3600000,
    fullText: '한국 해상풍력 8.2GW 로드맵 확정 산업통상자원부 발표 한국 korea 해상풍력 재생에너지 풍력',
  },
  {
    title: 'China Completes World\'s Largest Solar Farm in Xinjiang at 5GW Capacity',
    link: 'https://example.com/cn-solar-farm',
    snippet: 'China has connected the world\'s largest single-site solar farm to its grid in Xinjiang province. The 5GW facility spans 80,000 hectares and is paired with a 1.2GW battery storage system.',
    source: 'PV Magazine',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 5 * 3600000).toISOString(),
    timestamp: Date.now() - 5 * 3600000,
    fullText: 'China Completes World\'s Largest Solar Farm in Xinjiang at 5GW Capacity china chinese solar renewable energy beijing',
  },
  {
    title: 'India Sets New Renewable Energy Record: 200GW Installed Capacity Milestone',
    link: 'https://example.com/in-200gw',
    snippet: 'India has officially crossed the 200GW mark in total installed renewable energy capacity, driven by rapid solar deployment in Rajasthan and Gujarat. Prime Minister Modi called it a defining moment for the nation\'s energy transition.',
    source: 'CleanTechnica',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 6 * 3600000).toISOString(),
    timestamp: Date.now() - 6 * 3600000,
    fullText: 'India Sets New Renewable Energy Record 200GW Installed Capacity Milestone india indian modi solar renewable energy delhi',
  },
  {
    title: 'Japan Launches $4B Offshore Wind Expansion in Hokkaido and Akita',
    link: 'https://example.com/jp-offshore',
    snippet: 'Japan\'s METI announced a $4 billion offshore wind expansion targeting Hokkaido and Akita prefectures. The plan aims to add 3GW of capacity by 2028, with major contracts awarded to domestic and international developers.',
    source: 'Recharge News',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 7 * 3600000).toISOString(),
    timestamp: Date.now() - 7 * 3600000,
    fullText: 'Japan Launches $4B Offshore Wind Expansion in Hokkaido and Akita japan japanese meti tokyo offshore wind renewable energy',
  },
  {
    title: 'Australia\'s Snowy 2.0 Pumped Hydro Project Reaches 60% Completion',
    link: 'https://example.com/au-snowy',
    snippet: 'The Snowy 2.0 pumped hydro project in New South Wales has reached 60% completion. When finished, it will provide 2,000MW of dispatchable renewable energy storage, enough to power 500,000 homes for a week.',
    source: 'RenewEconomy',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 8 * 3600000).toISOString(),
    timestamp: Date.now() - 8 * 3600000,
    fullText: 'Australia\'s Snowy 2.0 Pumped Hydro Project Reaches 60% Completion australia australian snowy hydro renewable energy hydropower sydney',
  },
  {
    title: 'Global Wind Power Additions Hit Record 120GW in 2025',
    link: 'https://example.com/global-wind-record',
    snippet: 'The Global Wind Energy Council reported that worldwide wind power installations reached a record 120GW in 2025, with China accounting for nearly 60% of new capacity. Offshore wind grew 35% year-over-year.',
    source: 'BBC Sci & Env',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 10 * 3600000).toISOString(),
    timestamp: Date.now() - 10 * 3600000,
    fullText: 'Global Wind Power Additions Hit Record 120GW in 2025 wind power wind energy renewable energy global offshore wind',
  },
  {
    title: '한전, 제주 태양광·ESS 연계 마이크로그리드 실증 착수',
    link: 'https://example.com/kr-kepco-microgrid',
    snippet: 'KEPCO(한국전력)는 제주도에서 태양광 발전과 ESS를 연계한 마이크로그리드 실증사업에 착수했다. 이 프로젝트는 도서 지역의 에너지 자립률을 높이기 위한 핵심 사업이다.',
    source: '이투뉴스',
    lang: 'ko',
    image: null,
    pubDate: new Date(Date.now() - 12 * 3600000).toISOString(),
    timestamp: Date.now() - 12 * 3600000,
    fullText: '한전 제주 태양광 ESS 연계 마이크로그리드 실증 착수 KEPCO 한국 korea 태양광 재생에너지 에너지저장 스마트그리드',
  },
  {
    title: 'EU Carbon Border Tax Takes Effect, Reshaping Global Trade in Steel and Cement',
    link: 'https://example.com/eu-cbam',
    snippet: 'The EU Carbon Border Adjustment Mechanism (CBAM) is now fully operational, imposing carbon tariffs on imported steel, cement, aluminum, and fertilizers. The measure is expected to accelerate decarbonization efforts worldwide.',
    source: 'Reuters Sustainability',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 14 * 3600000).toISOString(),
    timestamp: Date.now() - 14 * 3600000,
    fullText: 'EU Carbon Border Tax Takes Effect Reshaping Global Trade european commission europe eu carbon tax decarbonization emissions trading',
  },
  {
    title: 'Texas Becomes Top U.S. State for Solar Installations, Surpassing California',
    link: 'https://example.com/us-texas-solar',
    snippet: 'Texas has officially overtaken California as the leading U.S. state for new solar installations in 2025, adding 12GW of utility-scale solar capacity. The state\'s vast open land and favorable policies drove rapid expansion.',
    source: 'NYT Climate',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 16 * 3600000).toISOString(),
    timestamp: Date.now() - 16 * 3600000,
    fullText: 'Texas Becomes Top U.S. State for Solar Installations Surpassing California united states u.s. usa solar renewable energy texas california',
  },
  {
    title: 'China Unveils Next-Gen Perovskite Solar Cell with 33.7% Efficiency',
    link: 'https://example.com/cn-perovskite',
    snippet: 'Chinese researchers have achieved a world-record 33.7% efficiency in tandem perovskite-silicon solar cells. The breakthrough could dramatically reduce the cost of solar energy and is expected to enter commercial production by 2027.',
    source: 'PV Magazine',
    lang: 'en',
    image: null,
    pubDate: new Date(Date.now() - 20 * 3600000).toISOString(),
    timestamp: Date.now() - 20 * 3600000,
    fullText: 'China Unveils Next-Gen Perovskite Solar Cell with 33.7% Efficiency china chinese solar photovoltaic renewable energy beijing',
  },
];

module.exports = sampleArticles;
